blank_issues_enabled: true
contact_links:
  - name: ğŸ” Looking for a channel
    url: https://007dimkos.github.io/dimmy-tv/discussions/categories/channel-search
    about: Need help finding a link to a channel stream
  - name: ğŸ’¡ Feature request
    url: https://007dimkos.github.io/dimmy-tv/discussions/categories/ideas
    about: For any ideas or feature requests
  - name: â“ Ask a question
    url: https://007dimkos.github.io/dimmy-tv/discussions/categories/q-a
    about: Ask questions about this project
